class Activities {
  static List activies = [
    {
      "title":"tasbeh",
      "image":"assets/tasbeh.png",
      "router":"/tasbeh_page",
    },
    {
      "title":"qiblar",
      "image":"assets/qiblah.jpeg",
      "router":"/compass",
    },
    {
      "title":"taqvim",
      "image":"assets/taqvim.png",
      "router":"/taqvim",
    },
    {
      "title":"qur'on",
      "image":"assets/quran.png",
      "router":"/quron",
    },
    {
      "title":"tahorat",
      "image":"assets/gusul.jpg",
      "router":"/tohorat",
    },
    {
      "title":"qazolar",
      "image":"assets/qazolar.png",
      "router":"/qazahs",
    },
  ];
}
